### ISSUE TITLE
Subtle cyborg overpowered rebalanced behaviour

### ISSUE THREAD

**Issue by cam-spacebar** [HumbleTS/Balance-Veteran-Patch#1]
Concerns with vet patch cyborgs:

Below I've written my thoughts on the vet patch cyborgs. It would be good to see this unit type used in "pro" matches, however there appear to be some unintended / subtle consequences of their rebalancing.

- increased range:
--- allows cyborgs to get off the first (higher powered shot) prior to opponent's standard infantry engaging
--- allows larger group of inf to have full engagement if cyborgs at back, while opponents back inf still need to run into position - they are unable to deliver hit points
--- allows easier popping of discs (with no walking)
--- Cyborgs do not need to run to target a new opponent - they can stand and deliver. Effectively meaning that they have more time delivering damage and less time moving into position and have an advantage over standard inf)

- increased damage
--- damage might be equivalent to same spend on standard inf, but damage does not atrophy as would damage dealt by 6 inf that die in succession. i.e. a cyborg delivers full damage until death, the equivalent 6 inf die off and lose their damage potential during the engagement.
--- increase damage is amplified by increased range (on first engagement and re-targetting - as no walking required)

- crushability
--- cyborgs can't be crushed, which makes harvs (in main) an ineffective defence.
--- harv bomb and standard infantry combination attacks are less effective against cyborgs

additional notes:
- Tiberian healing puts cyborgs at an additional advantage

**Comment by HumbleTS** [comment]
The modifications were not done based on simply the cost and firepower, etc.  The modifications were done after a ton of testing with varied infantry groups (all light inf, light inf with disc throwers) in different ratios that the sum of which was equal cost, and the testing was done by some of the best players in the game, such as cambria, skylegend, tight, mola, carnage, etc (near and away from tib fields).  If you simply group your infantry properly and control them properly and target light infantry first and cyborgs last, then they are really not all that hard to deal with.  Additionally, if you try making more than one or two cyborgs with your inf rush, you will find that you don't have enough economy to keep up with top tier players and also are not able to produce enough light infantry to be effective as a whole.  For starters I would recommend not making any disc throwers at all until you are able to better micro-manage your infantry groups vs pro players.

**Comment by HumbleTS** [comment]
Borgs have been nerfed since ur post

**Comment by cam-spacebar** [comment]
There's no new commits for this repo, the commit isn't here?

You can also close the issue if it doesn't require action.
